config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:index, :create] do
    collection do
      post :bulk_operation
    end
  end

  root 'pets#index'
  resources :kinds, controller: 'pet_kinds'
  resources :pets do
    collection do
      get 'hren'
    end
    resources :images, controller: 'pet_images' do
        member do
          post :set_default_image
        end
    end

  end

  # devise_for :users
  devise_for :users, controllers: {registrations: 'registrations' }
  # resources :users, path: 'my_users',only: [:index, :show, :edit]
  resources :users, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:new]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get ':uname' => 'pets#index', as: 'animal'

  # resources :pet_images

end

app/controllers/pet_kinds_controller.rb
class PetKindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]

  authorize_resource class: 'Pet::Kind'

  def index
    @pet_kinds = Pet::Kind.all
  end

  def show

  end

  def destroy
   @pet_kind.destroy
   respond_to do |format|
     format.html { redirect_to kinds_url, notice: 'Kind was finally destroyed' }
     format.json { head :no_content }
   end
  end

  def new
    @pet_kind= Pet::Kind.new
  end

  def create
    @pet_kind= Pet::Kind.new(kind_params)

    respond_to do |format|
      if @pet_kind.save
        format.html { redirect_to kind_path(@pet_kind), notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: kind_path(@pet_kind) }
      else
        format.html { render :new }
        format.json { render json: @pet_kind.errors, status: :unprocessable_entity }
      end
    end
   end





  private
      # Use callbacks to share common setup or constraints between actions.
      def set_kind
        @pet_kind= Pet::Kind.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def kind_params
        params.require(:pet_kind).permit(:name)
      end

  end

app/helpers/pet_kinds_helper.rb
module PetKindsHelper
end

app/views/pet_kinds/_form.html.slim
= simple_form_for @pet_kind, :url => kinds_path do |f|
  - if @pet_kind.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pet_kind.errors.count, "error")} prohibited this kind from being saved:"
      ul
        - @pet_kind.errors.full_messages.each do |message|
          li = message

  .ui.fields
    .field
      label Name
      = f.input_field :name
    p
    .actions = f.submit

app/views/pet_kinds/index.html.slim
h1 Pet's kinds 


table.ui.table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @pet_kinds.each do |kind|
      tr
        td = kind.name
        td = link_to 'Show', kind_path(kind)
        td = link_to 'Edit', kinds_path 
        td = link_to 'Destroy', kind_path(kind), data: {:confirm => 'Are you sure?'}, :method => :delete

br

# = link_to 'New kind', new_kind_path

app/views/pet_kinds/new.html.slim
h1 New kind 

== render 'form'
= link_to 'Back', kinds_path 

app/views/pet_kinds/show.html.slim
p#notice = notice

p
  strong Name:
  = @pet_kind.name
p

= link_to 'Edit', kind_path(@pet_kind) 
'|
= link_to 'Back',kinds_path 