config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:index, :create] do
    collection do
      post :bulk_operation
    end
  end

  root 'pets#index'
  resources :kinds, controller: 'pet_kinds'
  resources :pets do
    collection do
      get 'hren'
    end
    resources :images, controller: 'pet_images' do
        member do
          post :set_default_image
        end
    end

  end

  # devise_for :users
  devise_for :users, controllers: {registrations: 'registrations' }
  # resources :users, path: 'my_users',only: [:index, :show, :edit]
  resources :users, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:new]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get ':uname' => 'pets#index', as: 'animal'

  # resources :pet_images

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :user
  belongs_to :kind
  # accepts_nested_attributes_for :kind
  has_many :images

  belongs_to :default_image, foreign_key: :pet_image_id,
                             class_name: Pet::Image

  validates :kind, :name, presence: true
end

app/models/pet/image.rb
class Pet
  class Image < ActiveRecord::Base
    belongs_to :pet
    mount_uploader :image, ImageUploader
    validate :image_size

   private

      # Validates the size of an uploaded picture.
      def image_size
        if image.size > 5.megabytes
          errors.add(:image, "should be less than 1MB")
        end
      end
 end
end

app/models/pet/kind.rb
class Pet
  class Kind < ActiveRecord::Base
    has_many :pets

  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  authorize_resource

  # GET /pets
  # GET /pets.json
  def index
    if params[:uname] and  User.where(uname: params[:uname]).first then
      @user= User.where(uname: params[:uname]).first
      @pets = @user.pets
    else
      @user= current_user
      @pets = current_user.pets.all
    end
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = current_user.pets.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = current_user.pets.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :kind_id, :pet_image_id, :gender)
    end
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/_form.html.slim
 = simple_form_for @pet do |f|
  - if @pet.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pet.errors.count, "error")} prohibited this pet from being saved:"
      ul
        - @pet.errors.full_messages.each do |message|
          li = message

  .ui.fields
    .field
      label Name
      = f.input_field :name
    .field
      = f.association :kind, :label => 'Тип', hint: "#{ link_to ' new', new_kind_path }".html_safe 
    .field
      = f.input :gender, collection: ['м','ж'] 
    .actions = f.submit

app/views/pets/edit.html.slim
h1 Editing pet

== render 'form'

= link_to 'Show', @pet
'|
= link_to 'Back', pets_path

app/views/pets/index.html.slim
h1 = @user.uname + 's pets'


table.ui.table
  thead
    tr
      th Name
      th Kind
      th Gender
      th Images
      th
      th
      th

  tbody
    - @pets.each do |pet|
      tr
        td = pet.name
        td = Pet::Kind.find(pet.kind_id).name
        td = pet.gender
        td
          - pet.images.each do |img|
            img.ui.image.avatar.small src=img.image.try(:url)
        td = link_to 'Show', pet
        td = link_to 'Edit', edit_pet_path(pet)
        td = link_to 'Destroy', pet, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Pet', new_pet_path

app/views/pets/new.html.slim
h1 New pet

== render 'form'

= link_to 'Back', pets_path

app/views/pets/show.html.slim
p#notice = notice

p
  strong Name:
  = @pet.name

- if @pet.images.size > 0
  p
    .ui.image.medium = image_tag @pet.default_image.image.try(:url) if @pet.default_image
p
  strong Kind:
  = @pet.kind.name
p
  strong Gender:
  = @pet.gender

= link_to 'Edit', edit_pet_path(@pet)
'|
= link_to 'Back', pets_path
'|
= link_to 'Images', pet_images_path(@pet) 