config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:index, :create] do
    collection do
      post :bulk_operation
    end
  end

  root 'pets#index'
  resources :kinds, controller: 'pet_kinds'
  resources :pets do
    collection do
      get 'hren'
    end
    resources :images, controller: 'pet_images' do
        member do
          post :set_default_image
        end
    end

  end

  # devise_for :users
  devise_for :users, controllers: {registrations: 'registrations' }
  # resources :users, path: 'my_users',only: [:index, :show, :edit]
  resources :users, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:new]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get ':uname' => 'pets#index', as: 'animal'

  # resources :pet_images

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :uname, uniqueness: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pets
  has_many :messages, foreign_key: 'receiver_id'

  has_and_belongs_to_many :acceptable_pets, class_name: 'Pet::Kind',
    join_table: 'accepted_pet_kinds', association_foreign_key: 'pet_kind_id'

  def self.[] email_or_name
    candidates = where('email ILIKE ?', "%#{email_or_name}%")
    if candidates.size > 1
      raise "Many people found: #{candidates.map(&:email).to_sentence}"
    else candidates.first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit]
  authorize_resource

  def set_user
    @user = User.find(params[:id])
  end

  before_action :set_current_user, only: [:update, :edit]
  def set_current_user
    @user = current_user
  end

  def index
    @users = User.includes(pets: :images).order(:email)
  end


  def show
    if params[:email] then
      u = User.where(email: params[:email]).first
      bundle
      if u then
        @user = u
      end
    end
  end

  def email
    if params[:email] then
      u = User.where(email: params[:email]).first
      if u then
        @user = u
        redirect_to @user
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'user was successfully updated.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :uname, :lat, :lng)
  end
end

app/views/users/_balloon.html.slim
h1 = link_to user.uname, user_path(user)
/- user.pets.each do |pet|
/   img src=pet.images.first.try(:image).try(:url)

app/views/users/edit.html.slim
= form_for @user, url: user_path(@user) do |f|
  p
    = f.label :email
    = f.text_field :email
  p
    = f.label :lat
    = f.text_field :lat
  p
    = f.label :lng
    = f.text_field :lng
  p
    = f.label :uname
    = f.text_field :uname


  = f.submit 'Update'

- content_for :ymaps do
  script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"

h4 Update your location
div id='map' style="height: 500px; width: 1000px"

app/views/users/index.html.slim
- @users.each do |u|
  h1 = link_to u.email, user_path(u)

div id='map_index' style="height: 500px; width: 1000px"
- content_for :ymaps do
  script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"

coffee:
  # Дождёмся загрузки API и готовности DOM.
  unit = ->
    # Создание экземпляра карты и его привязка к контейнеру с
    # заданным id ("map").
    window.myMap = new (ymaps.Map)('map_index',
      center: [
        55.76
        37.64
      ]
      zoom: 10)

    $.get '/users.json', (users,status,c)->
      myMap.geoObjects.add(new ymaps.Placemark([u.lat,u.lng],
        hintContent: u.email,
        balloonContent: u.balloon)) for u in users

    #$.get '/users/1', (data)->
    #  alert data.uname
  
  ymaps.ready unit

app/views/users/show.html.slim
p#notice = notice
= 'Привет ' + @user.uname + '!'
p
  strong email:
  = @user.email
p
  strong lat:
  = @user.lat
p
  strong lng:
  = @user.lng
p
  strong Name:
  = @user.uname
p
  strong Accepted Kinds:
  ul
    - @user.acceptable_pets.each do |acc_pet| 
      li = acc_pet.name

= link_to 'Edit', edit_user_path(@user)
'|
= link_to 'Back', users_path
'|
= link_to 'Сообщения',new_user_message_path(@user)
'|
= link_to 'Животные', animal_path(@user.uname)

h4 Your location
div id='map' style="height: 500px; width: 800px"
- content_for :ymaps do
  script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"