config/routes.rb
Rails.application.routes.draw do

  resources :messages, only: [:index, :create] do
    collection do
      post :bulk_operation
    end
  end

  root 'pets#index'
  resources :kinds, controller: 'pet_kinds'
  resources :pets do
    collection do
      get 'hren'
    end
    resources :images, controller: 'pet_images' do
        member do
          post :set_default_image
        end
    end

  end

  # devise_for :users
  devise_for :users, controllers: {registrations: 'registrations' }
  # resources :users, path: 'my_users',only: [:index, :show, :edit]
  resources :users, only: [:index, :show, :edit, :update] do
    resources :messages, only: [:new]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get ':uname' => 'pets#index', as: 'animal'

  # resources :pet_images

end

app/controllers/pet_images_controller.rb
class PetImagesController < ApplicationController
  before_action do
    @pet = Pet.find params[:pet_id]
  end
  before_action :set_pet_image, only: [:show, :edit, :update, :destroy]
  authorize_resource class: 'Pet::Image'
  # GET /pet_images
  # GET /pet_images.json
  def index
    @pet_images = @pet.images.all
  end

  # GET /pet_images/1
  # GET /pet_images/1.json
  def show
  end

  # GET /pet_images/new
  def new
    @pet_image = @pet.images.new
  end

  # GET /pet_images/1/edit
  def edit
  end

  # POST /pet_images
  # POST /pet_images.json
  def create
    @pet_image = @pet.images.new(pet_image_params)

    respond_to do |format|
      if @pet_image.save
        # format.html { redirect_to pet_image_path(@pet, @pet_image), notice: 'Pet image was successfully created.' }
        format.html { redirect_to pet_images_path(@pet), notice: 'Pet image was successfully created.' }
        format.json { render :show, status: :created, location: @pet_image }
      else
        format.html { render :new }
        format.json { render json: @pet_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pet_images/1
  # PATCH/PUT /pet_images/1.json
  def update
    respond_to do |format|
      if @pet_image.update(pet_image_params)
        format.html { redirect_to @pet_image, notice: 'Pet image was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet_image }
      else
        format.html { render :edit }
        format.json { render json: @pet_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pet_images/1
  # DELETE /pet_images/1.json
  def destroy
    @pet_image.destroy
    respond_to do |format|
      format.html { redirect_to pet_images_url, notice: 'Pet image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def set_default_image
    default_image = params[:id]
    @pet.update(pet_image_id: default_image)

   redirect_to :back
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet_image
      @pet_image = @pet.images.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_image_params
      params[:pet_image].permit :image
    end
end

app/helpers/pet_images_helper.rb
module PetImagesHelper
end

app/views/pet_images/_form.html.slim
= simple_form_for @pet_image do |f|
  - if @pet_image.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pet_image.errors.count, "error")} prohibited this pet_image from being saved:"
      ul
        - @pet_image.errors.full_messages.each do |message|
          li = message
  = f.input :image, as: :file
  .actions = f.submit

app/views/pet_images/edit.html.slim
h1 Editing pet_image

== render 'form'

= link_to 'Show', pet_image_path(@pet, @pet_image)
'|
= link_to 'Back', pet_images_path(@pet)

app/views/pet_images/index.html.slim
h1 Галерея #{@pet.name}

table
  thead
    tr
      th
      th
      th

  .ui.four.cards
    - (@pet_images).each do |pet_image|
      .card
        .ui.image = image_tag pet_image.image.url
        -@pet_image = pet_image
        = link_to set_default_image_pet_image_path(id: pet_image.id),
          id: pet_image.id, class: 'button ui', method: :post do
          i.icon.photo
          | Назначить основным 


        /.header = pet_image.id

    
      br


/= link_to 'New Pet image', new_pet_image_path(@pet)
br

= link_to new_pet_image_path(@pet), class: 'button ui' do
  i.icon.photo
  | Добавить фото

/.ui.button 
  i.icon.photo
  /a href=new_pet_image_path(@pet)
    |Добавить фото
  = link_to 'Добавить фото', new_pet_image_path(@pet), class: 'link ui'
 

app/views/pet_images/new.html.slim
h1 New pet_image

== render 'form'

= link_to 'Back', pet_images_path

app/views/pet_images/show.html.slim
p#notice = notice


= link_to 'Edit', edit_pet_image_path(@pet,@pet_image)
'|
= link_to 'Back', pet_images_path